### ISSUE TITLE
For multilingual its not working

### ISSUE THREAD

**Issue by sachinp2014** [rjcoupe/ngx-tawk#3]
I have integrated it but I found that it is not working for multilingual websites, When we select the language from dropdown then we are changing its ID parameter value but its not loading the content of selected language.
Please resolve this issue!

**Comment by rjcoupe** [comment]
I'm not sure this is due to the Angular module. Nothing in the vanilla embed code relates to language (that I can see), and that's what ngx-tawk replicates.

Pull requests welcome if you can show that I'm wrong, of course!
